// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// monoSmooth_conditional
NumericVector monoSmooth_conditional(NumericVector pvalue, NumericVector density, IntegerVector group);
RcppExport SEXP _sffdr_monoSmooth_conditional(SEXP pvalueSEXP, SEXP densitySEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pvalue(pvalueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type density(densitySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(monoSmooth_conditional(pvalue, density, group));
    return rcpp_result_gen;
END_RCPP
}
// monoSmooth_pava
NumericVector monoSmooth_pava(NumericVector pvalue, NumericVector density, IntegerVector group);
RcppExport SEXP _sffdr_monoSmooth_pava(SEXP pvalueSEXP, SEXP densitySEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pvalue(pvalueSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type density(densitySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(monoSmooth_pava(pvalue, density, group));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sffdr_monoSmooth_conditional", (DL_FUNC) &_sffdr_monoSmooth_conditional, 3},
    {"_sffdr_monoSmooth_pava", (DL_FUNC) &_sffdr_monoSmooth_pava, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sffdr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
