# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

monoSmooth <- function(pvalue, z, density, window) {
    .Call('_sffdr_monoSmooth', PACKAGE = 'sffdr', pvalue, z, density, window)
}

